version: "2"
services:
    rabbitmq:
        image: rabbitmq
        ports:
          - "5672:5672"
        hostname: rabbitmq
    mariadb:
        build: mariadb
        hostname: mariadb
        environment:
          - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./db-data:/var/lib/mysql
        ports:
          - 3306:3306

    cinderclient:
        image: cinderclient:debian
        hostname: cinderclient
        links:
            - cinder-api
        environment:
            - OS_AUTH_TYPE=noauth
            - CINDERCLIENT_BYPASS_URL=http://cinder-api:8776/v3
            - OS_PROJECT_ID=foo
            - OS_VOLUME_API_VERSION=3.27

    cinder-api:
        image: loci_cinder:deb
        hostname: cinder-api
        volumes:
            - ./db-data:/var/lib/mysql
            - ./etc-cinder:/etc/cinder
            - ./init-scripts:/init-scripts
        ports:
            - 8776:8776
        links:
          - mariadb
          - rabbitmq
        depends_on:
          - mariadb
        command: sh /init-scripts/cinder.sh
    cinder-scheduler:
        image: loci_cinder:deb
        hostname: cinder-scheduler
        volumes:
            - ./db-data:/var/lib/mysql
            - ./etc-cinder:/etc/cinder
        links:
          - mariadb
          - rabbitmq
        depends_on:
          - mariadb
          - rabbitmq
        command: cinder-scheduler

    cinder-volume:
        image: loci_cinder:deb
        hostname: cinder-volume
        volumes:
            - ./db-data:/var/lib/mysql
            - ./etc-cinder:/etc/cinder
        links:
          - mariadb
          - rabbitmq
        depends_on:
          - mariadb
          - rabbitmq
        command: cinder-volume
